<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="saurabh-gloify" failures="1" tests="2" name="Test" time="73.786" errors="0" timestamp="2023-03-29T13:12:45 IST">
  <testcase classname="test.com.test.testclass" name="resetpass" time="16.001">
    <failure type="java.lang.AssertionError" message="expected [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/login] but found [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/lgin]">
      <![CDATA[java.lang.AssertionError: expected [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/login] but found [http://rnd-qa.s3-website.ap-south-1.amazonaws.com/lgin]
at test.com.test.testclass.resetpass(testclass.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- resetpass -->
  <testcase classname="test.com.test.testclass" name="title" time="1.925"/>
</testsuite> <!-- Test -->
